### ISSUE TITLE
Last image not loading

### ISSUE THREAD

**Issue by Tetragramm** [Sirosky/go-reader#1]
The last image of each comic is not loading properly.
Once scrolled to the bottom it reports 130 of 131.
You can also scroll past the bottom until it reports 146 of 131, and then you cannot always scroll back up and on occasion crash.

I have only tested on folders of images, but it happens on every set tested.

**Comment by Sirosky** [comment]
Hi, do you have the most recent release? 1.3.1 specifically.

**Comment by Tetragramm** [comment]
I was not, apparently.  Main is not up to date and that's what I was using.  I have switched to tag 1.3.1.

That fixes scrolling past the end and crashing, but the last page is still missing.

I should point out that the debug console reports the current page directory correctly with file name, but nothing appears on the screen.  IE: it shows the current page is blah/020.gif, but there is only background.

**Comment by Sirosky** [comment]
Ah yeah Main is not up to date, I should get around to merging 1.3. 

Can you upload a zip with the folder containing the 131 images in your library? I'll have to take a look at the structure to debug the issue.

Just saw your edit. Very odd. Could be an issue with Godot itself, but hopefully not.

**Comment by Tetragramm** [comment]
https://drive.google.com/file/d/1GVXp127k3KIdQ44CvrEVB93Fs_XcI3aF/view?usp=sharing

Only two images, and the second doesn't appear.  I don't see anything obviously different about the second image.

It's definitely not loading animated gif files, but this is just a jpg.

**Comment by Sirosky** [comment]
Found the issue but unfortunately it looks like there's nothing I can do about it :/

Godot currently does not support images greater than 16384 x 16384. There's an issue open on the Godot repository about this. I'll keep an eye on it and see if something changes. But until Godot does something about the max texture size, looks like go·reader won't be able to read such large images.

**Comment by Tetragramm** [comment]
Another set, this time well within the resolution limits.
https://drive.google.com/file/d/17Kv7AoZsWrRDGLhmtquSMd8G2r-L7Zwe/view?usp=sharing
Actually, it's just the second image.

**Comment by Sirosky** [comment]
Hate to say this, but once again, looks like an issue with Godot

https://i.imgur.com/ekpa1u2.png

Godot seems to have issues loading certain PNGs, for no apparent reason...

What's weirder is that when I change the problematic image's filetype to JPG, it loads just fine. FWIW I've read nearly 10k pages in go·reader, and only encountered this PNG loading issue on one set of chapters. It's an annoying issue, and I'm afraid there isn't really an elegant solution available. Sorry =/

**Comment by Tetragramm** [comment]
Is there a way to mark it with a placeholder so we can tell when it's failed?

**Comment by Sirosky** [comment]
Yeah that's a good idea. I'll add something in to let the user know if an image failed to load.

**Comment by Sirosky** [comment]
1.3.2 now warns the user if an image failed to load.
